# fly.toml app configuration file generated for server-morning-forest-197 on 2025-04-29T14:58:26Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-morning-forest-197"
primary_region = "sin"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
